Training and forecasting the solar power of Hokkaido Island in Japna
Training 2017, Forecast 2018

https://stackoverflow.com/questions/35139108/how-to-install-xgboost-in-anaconda-python-windows-platform

In [1]:
import pandas as pd
import numpy as np
import datetime as dt
import csv 
import matplotlib.pyplot as plt
import pytz
import xgboost as xgb

In [2]:
import os
cwd = os.getcwd()
cwd
# os.chdir('pvinhokkaidodatadistribution')
# C:\Users\Mhdella\Google Drive\Jupyter Folder\PV_Hokkaido_forecast_contest\
os.chdir('C:\\Users\\Mhdella\\Google Drive\\Jupyter Folder\\PV_Hokkaido_forecast_contest\\pvinhokkaidodatadistribution')
nwd=os.getcwd()
nwd

'C:\\Users\\Mhdella\\Google Drive\\Jupyter Folder\\PV_Hokkaido_forecast_contest\\pvinhokkaidodatadistribution'

In [3]:
# file_name='Merg_Ens_Agg_42_44_mes17_18.csv'
# file_name='Merg_Ens_Agg_43_mes17_18.csv'

# file_name='Merg_Ens_Agg_42_44_mes16_17_18.csv'

file_name='Merg_Ens_mmaxmin_Agg_42_44_mes16_18.csv'  ##This data are used before adjusing solar arradiacne

# file_name='Merg_Res_Comb_S1_S2_2018_tz_Jp.csv'
# file_mane='Merg_Res_Comb_S1_S2_2017_tz_Jp.csv'


df_hok=pd.read_csv(file_name) 
df_adjsol=pd.read_csv('Merg_Solar_Irrad_Ens_mmaxmin_Agg_42_44_16_18.csv',index_col=False) 
df_adjsol=df_adjsol.set_index('DATE_TIME')

df_hok.head()
# df_adjsol.head()

# df_hok.tail()

,DATE,TIME,S1[MW],S2[MW],solar[kW/m2],temp[deg C],solar[kW/m2].1,temp[deg C].1,solar[kW/m2].2,temp[deg C].2,...,t2m.2,asn.2,sd.2,ssrdc.2,ssrd.2,tcc.2,tciw.2,tclw.2,tp.2,wind_speed.2
0,1/1/2016,9:00:00,54.7,78.4,0.159228,-1.2,0.276627,0.0,0.339371,-5.9,...,-13.909399,0.600965,7.450000e-09,57.319398,30.413241,0.000000,0.000000,0.000000,0.000000e+00,7.704484
1,1/1/2016,9:30:00,113.8,89.0,0.221269,-0.3,0.307764,0.1,0.297246,-4.4,...,-12.694835,0.600870,7.450000e-09,104.414120,55.211142,0.037510,0.000396,0.000012,2.690000e-07,7.772519
2,1/1/2016,10:00:00,115.9,97.3,0.231619,-0.5,0.354492,0.7,0.320564,-2.3,...,-11.480271,0.600775,7.450000e-09,151.508843,80.009043,0.075021,0.000793,0.000023,5.390000e-07,7.840554
3,1/1/2016,10:30:00,139.5,100.6,0.205909,-0.4,0.363168,0.8,0.306980,-1.9,...,-10.265707,0.600680,7.450000e-09,198.603565,104.806944,0.112531,0.001189,0.000034,8.080000e-07,7.908589
4,1/1/2016,11:00:00,125.7,96.8,0.277444,-0.2,0.358989,0.6,0.237579,-3.1,...,-9.051143,0.600586,7.450000e-09,245.698287,129.604846,0.150041,0.001585,0.000046,1.080000e-06,7.976625

In [4]:
#### This cell just to check out the dataset with different coordination lat 43 and lat42-44 from ECMWF
df_hok1=pd.read_csv('Merg_Ens_Agg_42_44_mes17_18.csv') 
df_hok2=pd.read_csv('Merg_Ens_Agg_43_mes17_18.csv')

df_mns= {'col1': df_hok1.mean(), 'col2': df_hok2.mean()}
# df_mns

https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.GradientBoostingRegressor.html

https://scikit-learn.org/stable/auto_examples/ensemble/plot_gradient_boosting_regression.html#sphx-glr-auto-examples-ensemble-plot-gradient-boosting-regression-py

In [5]:
import sklearn 
import numpy as np
from sklearn.metrics import mean_squared_error
# X, y = make_friedman1(n_samples=1200, random_state=0, noise=1.0)
# X, y = make_friedman1(n_samples=1200, random_state=0, noise=1.0)
df_hok.head()

,DATE,TIME,S1[MW],S2[MW],solar[kW/m2],temp[deg C],solar[kW/m2].1,temp[deg C].1,solar[kW/m2].2,temp[deg C].2,...,t2m.2,asn.2,sd.2,ssrdc.2,ssrd.2,tcc.2,tciw.2,tclw.2,tp.2,wind_speed.2
0,1/1/2016,9:00:00,54.7,78.4,0.159228,-1.2,0.276627,0.0,0.339371,-5.9,...,-13.909399,0.600965,7.450000e-09,57.319398,30.413241,0.000000,0.000000,0.000000,0.000000e+00,7.704484
1,1/1/2016,9:30:00,113.8,89.0,0.221269,-0.3,0.307764,0.1,0.297246,-4.4,...,-12.694835,0.600870,7.450000e-09,104.414120,55.211142,0.037510,0.000396,0.000012,2.690000e-07,7.772519
2,1/1/2016,10:00:00,115.9,97.3,0.231619,-0.5,0.354492,0.7,0.320564,-2.3,...,-11.480271,0.600775,7.450000e-09,151.508843,80.009043,0.075021,0.000793,0.000023,5.390000e-07,7.840554
3,1/1/2016,10:30:00,139.5,100.6,0.205909,-0.4,0.363168,0.8,0.306980,-1.9,...,-10.265707,0.600680,7.450000e-09,198.603565,104.806944,0.112531,0.001189,0.000034,8.080000e-07,7.908589
4,1/1/2016,11:00:00,125.7,96.8,0.277444,-0.2,0.358989,0.6,0.237579,-3.1,...,-9.051143,0.600586,7.450000e-09,245.698287,129.604846,0.150041,0.001585,0.000046,1.080000e-06,7.976625

In [6]:
print(list(df_hok))

['DATE', 'TIME', 'S1[MW]', 'S2[MW]', 'solar[kW/m2]', 'temp[deg C]', 'solar[kW/m2].1', 'temp[deg C].1', 'solar[kW/m2].2', 'temp[deg C].2', 'solar[kW/m2].3', 'temp[deg C].3', 'u10', 'v10', 't2m', 'asn', 'sd', 'ssrdc', 'ssrd', 'tcc', 'tciw', 'tclw', 'tp', 'wind_speed', 'u10.1', 'v10.1', 't2m.1', 'asn.1', 'sd.1', 'ssrdc.1', 'ssrd.1', 'tcc.1', 'tciw.1', 'tclw.1', 'tp.1', 'wind_speed.1', 'u10.2', 'v10.2', 't2m.2', 'asn.2', 'sd.2', 'ssrdc.2', 'ssrd.2', 'tcc.2', 'tciw.2', 'tclw.2', 'tp.2', 'wind_speed.2']

In [7]:
#### df_feats=df_hok[df_hok['ssrdc'] != 0] ## dropping night hours, when clear-sky solar irradiance (SSRDC) forecasts=0, and this can be applied in real forecasts  

#### df_feats=df_hok.set_index('DATE')

############################# Not dropping night hours   ####### And add adjusted solar irradiance as new feature

df_tar_feats=df_hok.set_index(pd.to_datetime(df_hok['DATE'] + ' ' + df_hok['TIME']))

df_adjsol.index=pd.to_datetime(df_adjsol.index)
df_tar_feats['adj_ssrd']=df_adjsol['Ypd']

df_adjsol.head()
df_tar_feats.head()
len(df_tar_feats)
df_tar_feats['adj_ssrd'] = df_tar_feats['adj_ssrd'].replace(np.nan, 0, regex=True)
df_tar_feats['adj_ssrd'].isna().sum()  #There was 13 enteries as Nan and now they are set to 0.

############## In case of forecast solar power  #######

Targ=df_tar_feats['S1[MW]']+df_tar_feats['S2[MW]']
Targ = Targ.replace(np.nan, 0, regex=True)

df_feats=df_tar_feats[['u10', 'v10', 't2m', 'asn', 'sd', 'ssrdc', 'tcc', 'tciw', 'tclw', 'tp', 'wind_speed', 
             'u10.1', 'v10.1', 't2m.1', 'asn.1', 'sd.1', 'ssrdc.1', 'ssrd.1', 'tcc.1', 'tciw.1', 'tclw.1', 'tp.1', 'wind_speed.1', 
             'u10.2', 'v10.2', 't2m.2', 'asn.2', 'sd.2', 'ssrdc.2', 'ssrd.2', 'tcc.2', 'tciw.2', 'tclw.2', 'tp.2', 
                       'wind_speed.2', 'adj_ssrd']]
############### In case of forecast solar irradiance  #######

# Targ=df_tar_feats['ssrd']  #ssrd is the mean of ssrd data from all ensemble members
# df_feats=df_tar_feats[['u10', 'v10', 't2m', 'asn', 'sd', 'ssrdc', 'tcc', 'tciw', 'tclw', 'tp', 'wind_speed', 
#              'u10.1', 'v10.1', 't2m.1', 'asn.1', 'sd.1', 'ssrdc.1', 'tcc.1', 'tciw.1', 'tclw.1', 'tp.1', 'wind_speed.1', 
#              'u10.2', 'v10.2', 't2m.2', 'asn.2', 'sd.2', 'ssrdc.2', 'tcc.2', 'tciw.2', 'tclw.2', 'tp.2', 'wind_speed.2']]


df_tar_feats.insert(loc=0, column='Targ', value=Targ)

df_feats.head()
df_feats.tail()

print(len(list(df_feats)), len(list(df_tar_feats)))
# Targ.tail()

36 50

In [8]:
len(df_feats)
# len(Targ)
print(len(Targ), max(Targ), Targ.mean())
# df_tar_feats.head()

52603 312.6 37.385689029143066

In [9]:
# ind_date_time= pd.date_range('2019-03-08 00:00','2019-03-09 00:00',freq='120T')
ind_date_time= pd.date_range('2019-03-08 04:00','2019-03-09 03:30',freq='30T')

Hours= ind_date_time.strftime('%H:%M')
# Hours
# for num in range(0,len(Hours),6):
#     print(Hours[num])

In [10]:
df_intrv0=df_tar_feats.between_time('20:00','03:30')
df_intrv1=df_tar_feats.between_time('04:00','07:30')
df_intrv2=df_tar_feats.between_time('08:00','11:30')
df_intrv3=df_tar_feats.between_time('12:00','15:30')
df_intrv4=df_tar_feats.between_time('16:00','19:30')
# df_intrv4.head(9)

In [18]:
#df=dfdfd #Just to stop before run the following cell

In [25]:
from Hokk_Hourly_Forecast_Models import model_intrv0, model_intrv1, model_intrv2, model_intrv3, model_intrv4
intvs=[df_intrv0, df_intrv1, df_intrv2, df_intrv3, df_intrv4]
for num in range(0, len(intvs)):
    df_hr=intvs[num]
#     print(num, len(df_hr), max(df_hr['Targ']), df_hr['Targ'].mean(), df_hr['Targ'].std())
    
    ####Select features of the data 
    Targ=df_hr['Targ']
    df_feats_w_mes=df_hr.drop('Targ', axis=1) #Features including measurements and weather forecasts
    df_feats_no_mes =df_hr.drop(df_tar_feats.columns[range(0,13)], axis=1)  #Features of weather forecasts only
    df_feats_no_mes=df_feats_no_mes.drop('ssrd', axis=1) #Features not including ssrd mean form ECMWF

    # df_feats=df_feats_w_mes  ## the measurements lenght is less than the weather since there are not exist in forecast period
    df_feats=df_feats_no_mes   
    X_train=df_feats.loc['1/1/2016':'12/31/2016']
    X_test=df_feats.loc['1/1/2017':'12/31/2017']

    # X_train=df_feats.loc['1/1/2017':'12/31/2017']
    # X_test=df_feats.loc['1/1/2018':'12/31/2018']

    Y_train=Targ.loc['1/1/2016':'12/31/2016']
    Y_test=Targ.loc['1/1/2017':'12/31/2017']

    # Y_train=Targ.loc['1/1/2017':'12/31/2017']
    # Y_test=Targ.loc['1/1/2018':'12/31/2018']

    X_train.head()
    # X_train.tail()
    # len(X_train)

    # Y_train.head()
    # len(Y_train)
    Y_train.tail()
    
    if num==0:
        print('Yes20:00-3:30')
        reslts=model_intrv0(Y_train, X_train, Y_test, X_test, Targ)
        st0={'mse': reslts['mse'], 'nRMSE':reslts['nRMSE']}
        Ytspd_inv0=reslts['Yts_pd']    
    elif num==1:
        print('Yes4:00-7:30')
        reslts=model_intrv1(Y_train, X_train, Y_test, X_test, Targ)
        st1={'mse': reslts['mse'], 'nRMSE':reslts['nRMSE']}
        Ytspd_inv1=reslts['Yts_pd'] 
    elif num==2:
        print('Yes8:00-11:30')
        reslts=model_intrv2(Y_train, X_train, Y_test, X_test, Targ) 
        st2={'mse': reslts['mse'], 'nRMSE':reslts['nRMSE']}
        Ytspd_inv2=reslts['Yts_pd']  
    elif num==3:
        print('Yes12:00-15:30')
        reslts=model_intrv3(Y_train, X_train, Y_test, X_test, Targ)
        st3={'mse': reslts['mse'], 'nRMSE':reslts['nRMSE']}
        Ytspd_inv3=reslts['Yts_pd'] 
    elif num==4:
        print('Yes16:00-19:30')
        reslts=model_intrv3(Y_train, X_train, Y_test, X_test, Targ)
        st4={'mse': reslts['mse'], 'nRMSE':reslts['nRMSE']}
        Ytspd_inv4=reslts['Yts_pd']     
    else:
        print('No')

Yes20:00-3:30

C:\Users\Mhdella\Google Drive\Jupyter Folder\PV_Hokkaido_forecast_contest\Forecast_codes\Hokk_Hourly_Forecast_Models.py:17: RuntimeWarning: divide by zero encountered in double_scalars
  nRMSE=np.sqrt(mse)/Targ.mean()

3.552713678800501e-15 inf
Yes4:00-7:30
285.61774103318476 0.948222767814302
Yes8:00-11:30
2475.298219549889 0.4524491996371222
Yes12:00-15:30
2398.137048421519 0.5425907568004729
Yes16:00-19:30
51.252171427531245 1.1390728054270727

In [28]:
sYs=sum([len(Ytspd_inv0), len(Ytspd_inv1), len(Ytspd_inv2), len(Ytspd_inv3), len(Ytspd_inv4)])
print(sYs, len(df_tar_feats['Targ'].loc['1/1/2017':'12/31/2017']))

17520 17520

In [29]:
Ytspd_inv0[Ytspd_inv0>0]=0
Ytspd_inv0[Ytspd_inv0<0]=0

print(len(Ytspd_inv0))
# Ytspd_inv0.head()

5840

In [30]:
df_ytgfst= pd.concat([Ytspd_inv0, Ytspd_inv1, Ytspd_inv2, Ytspd_inv3, Ytspd_inv4])
df_ytgfst.sort_index(inplace=True)
df_ytgfst.head()
df_ytgfst.tail()

                     Yts  Ypd
2017-12-31 21:30:00  0.0  0.0
2017-12-31 22:00:00  0.0  0.0
2017-12-31 22:30:00  0.0  0.0
2017-12-31 23:00:00  0.0  0.0
2017-12-31 23:30:00  0.0  0.0

In [31]:
MSE=mean_squared_error(df_ytgfst['Yts'], df_ytgfst['Ypd'])  
# NRMSE=np.sqrt(MSE)/df_ytgfst['Yts'].mean()  #mean of target solar power during 2017 only
NRMSE=np.sqrt(MSE)/df_tar_feats['Targ'].mean()  #mean of target solar power durning 2016 and 2017

print(MSE, NRMSE)

868.3841967386873 0.7882256556649574

Run XGBoost models of four intervals to forecast solar power entire 2017, leads to:

3.552713678800501e-15 inf
Yes4:00-7:30
252.1004035647795 0.8908499489261236
Yes8:00-11:30
2195.7784140037934 0.4261380510120714
Yes12:00-15:30
2175.378331643344 0.5167765414509862
Yes16:00-19:30
47.106641460703656 1.0920346515994597

Based on nRMSE results, the most challenging hours to forecasts are morning and evening hours(4 to 8 and 16 to 20).

print(MSE, NRMSE)=778.3939651121035,  0.7462671776141188

It was by using one XGBoost model for all hours, print(mse, nRMSE)= 2148.8480, 1.2399

Therefore, the improvement between using one forecasting model and 4 models: (1.2399-0.74627)/1.2399*100=40%


If the normalization RMSE was by the maximum output (not the mean)
0.7462671776141188*df_tar_feats['Targ'].mean()/max(df_tar_feats['Targ'])=0.08925%

By including adjusted solar irradiance as a new feature, the nRMSE increased (not imporved):
print(MSE, NRMSE)=866.2967424948833,  0.7872777025608771>0.74  (adj Solar added manually form csv or by merging based on inded Date-time, in both cases gives nRMSE= 0.78).

Thus, the adjusted solar leads to worse forecasts, the reason might be the ground measurements of solar irradiance are not calibrated well to adjust solar irradiance from the ECMWF.

Tried using adj ssrd but without the ssrd from ECMWF in the features, got:
print(MSE, NRMSE)=868.3841967386873 0.7882256556649574 (Still>0.74 without adj solar)

0.7494011773420667*df_tar_feats['Targ'].mean()/max(df_tar_feats['Targ'])=0.0896% after CV=0.087478 (improv=2.4%)

In [ ]:
print(len(Ytspd_inv0), len(Ytspd_inv1), len(Ytspd_inv2), len(Ytspd_inv3), len(Ytspd_inv4))

In [ ]:
0.7462671776141188*df_tar_feats['Targ'].mean()/max(df_tar_feats['Targ'])

In [ ]:
(1.2399-0.746267)/1.2399*100

In [ ]:
df_ytgfst['Yts'].mean()

In [ ]:
###Just to check NRMSE from nRMSEs of each interval, although using the Ytarget and Yprd is the actaul NRMSE
###0.731 almost equals to 0.749
(1.0920346515994597+0.5167765414509862+0.4261380510120714+0.8908499489261236)/4

In [24]:
X_train.head()

,u10,v10,t2m,asn,sd,ssrdc,tcc,tciw,tclw,tp,...,asn.2,sd.2,ssrdc.2,ssrd.2,tcc.2,tciw.2,tclw.2,tp.2,wind_speed.2,adj_ssrd
2016-01-01 16:00:00,4.712861,-3.010843,-2.048350,0.827225,0.015783,201.655400,0.777592,0.014445,0.019775,0.000094,...,0.600731,7.450000e-09,176.033889,90.242284,0.068525,0.000264,0.000023,0.0,7.795545,-0.693695
2016-01-01 16:30:00,4.647021,-2.765225,-2.240616,0.827152,0.015785,155.433640,0.748314,0.013505,0.021202,0.000086,...,0.600596,7.450000e-09,134.435509,68.802164,0.053134,0.000198,0.000017,0.0,7.699937,-0.992844
2016-01-01 17:00:00,4.581182,-2.519606,-2.432882,0.827078,0.015786,109.211880,0.719035,0.012565,0.022629,0.000078,...,0.600461,7.450000e-09,92.837130,47.362045,0.037742,0.000132,0.000012,0.0,7.604328,-1.032522
2016-01-01 17:30:00,4.515342,-2.273988,-2.625148,0.827005,0.015788,62.990130,0.689757,0.011625,0.024056,0.000070,...,0.600326,7.450000e-09,51.238750,25.921925,0.022350,0.000066,0.000006,0.0,7.508719,-1.025011
2016-01-01 18:00:00,4.449503,-2.028370,-2.817413,0.826932,0.015789,16.768377,0.660479,0.010685,0.025483,0.000062,...,0.600191,7.450000e-09,9.640370,4.481806,0.006958,0.000000,0.000000,0.0,7.413111,-1.044320