Training and forecasting the solar power of Hokkaido Island in Japna
Training 2017, Forecast 2018

https://stackoverflow.com/questions/35139108/how-to-install-xgboost-in-anaconda-python-windows-platform

In [129]:
import pandas as pd
import numpy as np
import datetime as dt
import csv 
import matplotlib.pyplot as plt
import pytz
import xgboost as xgb

In [130]:
import os
cwd = os.getcwd()
cwd
# os.chdir('pvinhokkaidodatadistribution')
# C:\Users\Mhdella\Google Drive\Jupyter Folder\PV_Hokkaido_forecast_contest\
os.chdir('C:\\Users\\Mhdella\\Google Drive\\Jupyter Folder\\PV_Hokkaido_forecast_contest\\pvinhokkaidodatadistribution')
nwd=os.getcwd()
nwd

'C:\\Users\\Mhdella\\Google Drive\\Jupyter Folder\\PV_Hokkaido_forecast_contest\\pvinhokkaidodatadistribution'

In [131]:
# file_name='Merg_Ens_Agg_42_44_mes17_18.csv'
# file_name='Merg_Ens_Agg_43_mes17_18.csv'

# file_name='Merg_Ens_Agg_42_44_mes16_17_18.csv'
file_name='Merg_Ens_mmaxmin_Agg_42_44_mes16_18.csv'

# file_name='Merg_Res_Comb_S1_S2_2018_tz_Jp.csv'
# file_mane='Merg_Res_Comb_S1_S2_2017_tz_Jp.csv'

df_hok=pd.read_csv(file_name) 
df_hok.head()
# df_hok.tail()

,DATE,TIME,S1[MW],S2[MW],solar[kW/m2],temp[deg C],solar[kW/m2].1,temp[deg C].1,solar[kW/m2].2,temp[deg C].2,...,t2m.2,asn.2,sd.2,ssrdc.2,ssrd.2,tcc.2,tciw.2,tclw.2,tp.2,wind_speed.2
0,1/1/2016,9:00:00,54.7,78.4,0.159228,-1.2,0.276627,0.0,0.339371,-5.9,...,-13.909399,0.600965,7.450000e-09,57.319398,30.413241,0.000000,0.000000,0.000000,0.000000e+00,7.704484
1,1/1/2016,9:30:00,113.8,89.0,0.221269,-0.3,0.307764,0.1,0.297246,-4.4,...,-12.694835,0.600870,7.450000e-09,104.414120,55.211142,0.037510,0.000396,0.000012,2.690000e-07,7.772519
2,1/1/2016,10:00:00,115.9,97.3,0.231619,-0.5,0.354492,0.7,0.320564,-2.3,...,-11.480271,0.600775,7.450000e-09,151.508843,80.009043,0.075021,0.000793,0.000023,5.390000e-07,7.840554
3,1/1/2016,10:30:00,139.5,100.6,0.205909,-0.4,0.363168,0.8,0.306980,-1.9,...,-10.265707,0.600680,7.450000e-09,198.603565,104.806944,0.112531,0.001189,0.000034,8.080000e-07,7.908589
4,1/1/2016,11:00:00,125.7,96.8,0.277444,-0.2,0.358989,0.6,0.237579,-3.1,...,-9.051143,0.600586,7.450000e-09,245.698287,129.604846,0.150041,0.001585,0.000046,1.080000e-06,7.976625

In [132]:
#### This cell just to check out the dataset with different coordination lat 43 and lat42-44 from ECMWF
df_hok1=pd.read_csv('Merg_Ens_Agg_42_44_mes17_18.csv') 
df_hok2=pd.read_csv('Merg_Ens_Agg_43_mes17_18.csv')

df_mns= {'col1': df_hok1.mean(), 'col2': df_hok2.mean()}
# df_mns

https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.GradientBoostingRegressor.html

https://scikit-learn.org/stable/auto_examples/ensemble/plot_gradient_boosting_regression.html#sphx-glr-auto-examples-ensemble-plot-gradient-boosting-regression-py

In [133]:
import sklearn 
import numpy as np
from sklearn.metrics import mean_squared_error
from sklearn.datasets import make_friedman1
# X, y = make_friedman1(n_samples=1200, random_state=0, noise=1.0)
# X, y = make_friedman1(n_samples=1200, random_state=0, noise=1.0)
df_hok.head()

,DATE,TIME,S1[MW],S2[MW],solar[kW/m2],temp[deg C],solar[kW/m2].1,temp[deg C].1,solar[kW/m2].2,temp[deg C].2,...,t2m.2,asn.2,sd.2,ssrdc.2,ssrd.2,tcc.2,tciw.2,tclw.2,tp.2,wind_speed.2
0,1/1/2016,9:00:00,54.7,78.4,0.159228,-1.2,0.276627,0.0,0.339371,-5.9,...,-13.909399,0.600965,7.450000e-09,57.319398,30.413241,0.000000,0.000000,0.000000,0.000000e+00,7.704484
1,1/1/2016,9:30:00,113.8,89.0,0.221269,-0.3,0.307764,0.1,0.297246,-4.4,...,-12.694835,0.600870,7.450000e-09,104.414120,55.211142,0.037510,0.000396,0.000012,2.690000e-07,7.772519
2,1/1/2016,10:00:00,115.9,97.3,0.231619,-0.5,0.354492,0.7,0.320564,-2.3,...,-11.480271,0.600775,7.450000e-09,151.508843,80.009043,0.075021,0.000793,0.000023,5.390000e-07,7.840554
3,1/1/2016,10:30:00,139.5,100.6,0.205909,-0.4,0.363168,0.8,0.306980,-1.9,...,-10.265707,0.600680,7.450000e-09,198.603565,104.806944,0.112531,0.001189,0.000034,8.080000e-07,7.908589
4,1/1/2016,11:00:00,125.7,96.8,0.277444,-0.2,0.358989,0.6,0.237579,-3.1,...,-9.051143,0.600586,7.450000e-09,245.698287,129.604846,0.150041,0.001585,0.000046,1.080000e-06,7.976625

In [134]:
print(list(df_hok))

['DATE', 'TIME', 'S1[MW]', 'S2[MW]', 'solar[kW/m2]', 'temp[deg C]', 'solar[kW/m2].1', 'temp[deg C].1', 'solar[kW/m2].2', 'temp[deg C].2', 'solar[kW/m2].3', 'temp[deg C].3', 'u10', 'v10', 't2m', 'asn', 'sd', 'ssrdc', 'ssrd', 'tcc', 'tciw', 'tclw', 'tp', 'wind_speed', 'u10.1', 'v10.1', 't2m.1', 'asn.1', 'sd.1', 'ssrdc.1', 'ssrd.1', 'tcc.1', 'tciw.1', 'tclw.1', 'tp.1', 'wind_speed.1', 'u10.2', 'v10.2', 't2m.2', 'asn.2', 'sd.2', 'ssrdc.2', 'ssrd.2', 'tcc.2', 'tciw.2', 'tclw.2', 'tp.2', 'wind_speed.2']

In [135]:
#### df_feats=df_hok[df_hok['ssrdc'] != 0] ## dropping night hours, when clear-sky solar irradiance (SSRDC) forecasts=0, and this can be applied in real forecasts  

#### df_feats=df_hok.set_index('DATE')

############################# Not dropping night hours

df_tar_feats=df_hok.set_index(pd.to_datetime(df_hok['DATE'] + ' ' + df_hok['TIME']))

############## In case of forecast solar power  #######

Targ=df_tar_feats['S1[MW]']+df_tar_feats['S2[MW]']
Targ = Targ.replace(np.nan, 0, regex=True)

df_feats=df_tar_feats[['u10', 'v10', 't2m', 'asn', 'sd', 'ssrdc', 'ssrd', 'tcc', 'tciw', 'tclw', 'tp', 'wind_speed', 
             'u10.1', 'v10.1', 't2m.1', 'asn.1', 'sd.1', 'ssrdc.1', 'ssrd.1', 'tcc.1', 'tciw.1', 'tclw.1', 'tp.1', 'wind_speed.1', 
             'u10.2', 'v10.2', 't2m.2', 'asn.2', 'sd.2', 'ssrdc.2', 'ssrd.2', 'tcc.2', 'tciw.2', 'tclw.2', 'tp.2', 'wind_speed.2']]
############### In case of forecast solar irradiance  #######

# Targ=df_tar_feats['ssrd']  #ssrd is the mean of ssrd data from all ensemble members
# df_feats=df_tar_feats[['u10', 'v10', 't2m', 'asn', 'sd', 'ssrdc', 'tcc', 'tciw', 'tclw', 'tp', 'wind_speed', 
#              'u10.1', 'v10.1', 't2m.1', 'asn.1', 'sd.1', 'ssrdc.1', 'tcc.1', 'tciw.1', 'tclw.1', 'tp.1', 'wind_speed.1', 
#              'u10.2', 'v10.2', 't2m.2', 'asn.2', 'sd.2', 'ssrdc.2', 'tcc.2', 'tciw.2', 'tclw.2', 'tp.2', 'wind_speed.2']]


df_tar_feats.insert(loc=0, column='Targ', value=Targ)

df_feats.head()
df_feats.tail()

print(len(list(df_feats)), len(list(df_tar_feats)))
# Targ.tail()

36 49

In [136]:
len(df_feats)
# len(Targ)
print(len(Targ), max(Targ), Targ.mean())

52603 312.6 37.385689029143066

In [137]:
X_train=df_feats.loc['1/1/2016':'12/31/2016']
X_test=df_feats.loc['1/1/2017':'12/31/2017']

# X_train=df_feats.loc['1/1/2017':'12/31/2017']
# X_test=df_feats.loc['1/1/2018':'12/31/2018']

Y_train=Targ.loc['1/1/2016':'12/31/2016']
Y_test=Targ.loc['1/1/2017':'12/31/2017']

# Y_train=Targ.loc['1/1/2017':'12/31/2017']
# Y_test=Targ.loc['1/1/2018':'12/31/2018']

X_train.head()
X_train.tail()
len(X_train)

# Y_train.head()
# len(Y_train)
Y_train.tail()

2016-12-31 21:30:00    0.0
2016-12-31 22:00:00    0.0
2016-12-31 22:30:00    0.0
2016-12-31 23:00:00    0.0
2016-12-31 23:30:00    0.0
dtype: float64

In [138]:
df_feats2=df_tar_feats.drop('Targ', axis=1) #features of measurements and weather forecasts
df_feats3 = df_tar_feats.drop(df_tar_feats.columns[range(0,13)], axis=1)  #features of weather forecasts
# print(len(list(df_feats)), len(list(df_tar_feats)))
# df_tar_feats.head()
# df_feats.head()
# df_feats2.head()
# df_feats3.head()

In [146]:
hr='00:00'
hrs=hr[:-3]
'df_hr'+hrs
ind_date_time= pd.date_range('2019-03-08 00:00','2019-03-08 23:30',freq='30T')
# ind_date_time= pd.date_range('2019-03-08 00:00','2019-03-09 00:00',freq='90T')

Hours=ind_date_time.strftime('%H:%M')
print(len(Hours))
Hours
# pd.date_range('00:00','00:00',freq='60T')
# Hours[1]
# range(0,len(Hours)-1)
# Hours[1][:-3]
# df_hr=df_tar_feats.between_time('00:00','00:30')

df_hr.head(9)

48

,Targ,DATE,TIME,S1[MW],S2[MW],solar[kW/m2],temp[deg C],solar[kW/m2].1,temp[deg C].1,solar[kW/m2].2,...,t2m.2,asn.2,sd.2,ssrdc.2,ssrd.2,tcc.2,tciw.2,tclw.2,tp.2,wind_speed.2
2016-01-01 23:00:00,0.0,1/1/2016,23:00:00,0.0,0.0,-0.000914,-2.8,-0.000971,-3.2,-0.000907,...,-14.874915,0.598475,7.450000e-09,0.0,0.0,0.018576,0.000111,0.0,0.0,3.641058
2016-01-01 23:30:00,0.0,1/1/2016,23:30:00,0.0,0.0,-0.000473,-2.9,-0.000877,-3.1,-0.000732,...,-14.778769,0.598309,7.450000e-09,0.0,0.0,0.023220,0.000135,0.0,0.0,3.332800
2016-01-02 23:00:00,0.0,1/2/2016,23:00:00,0.0,0.0,-0.002175,2.0,-0.002222,1.6,-0.002191,...,-9.295264,0.595360,7.450000e-09,0.0,0.0,0.000000,0.000000,0.0,0.0,5.920933
2016-01-02 23:30:00,0.0,1/2/2016,23:30:00,0.0,0.0,-0.000750,1.8,-0.001514,1.6,-0.001166,...,-9.287878,0.595201,7.450000e-09,0.0,0.0,0.000000,0.000000,0.0,0.0,5.907053
2016-01-03 23:00:00,0.0,1/3/2016,23:00:00,0.0,0.0,-0.000034,-1.7,-0.001200,-4.1,-0.001293,...,-11.138536,0.585427,7.450000e-09,0.0,0.0,0.078083,0.000243,0.0,0.0,3.768079
2016-01-03 23:30:00,0.0,1/3/2016,23:30:00,0.0,0.0,-0.000314,-3.8,-0.001366,-4.0,-0.000998,...,-11.325466,0.585260,7.450000e-09,0.0,0.0,0.039041,0.000122,0.0,0.0,3.680238
2016-01-04 23:00:00,0.0,1/4/2016,23:00:00,0.0,0.0,-0.000294,-6.9,-0.001851,-5.2,-0.001140,...,-15.255713,0.577553,7.450000e-09,0.0,0.0,0.000000,0.000000,0.0,0.0,6.760098
2016-01-04 23:30:00,0.0,1/4/2016,23:30:00,0.0,0.0,-0.000562,-8.0,-0.001534,-6.7,-0.000856,...,-15.579047,0.577386,7.450000e-09,0.0,0.0,0.000000,0.000000,0.0,0.0,6.918806
2016-01-05 23:00:00,0.0,1/5/2016,23:00:00,0.0,0.0,-0.000755,-4.2,-0.001239,-6.4,-0.001775,...,-14.492061,0.570166,7.450000e-09,0.0,0.0,0.000000,0.000000,0.0,0.0,7.026277

In [145]:
## R=dfddf ### Just to stop to check out before run forecast models

ind_date_time= pd.date_range('2019-03-08 00:00','2019-03-08 23:30',freq='30T')

Hours= ind_date_time.strftime('%H:%M')

for num in range(0,len(Hours),2):
    hr=Hours[num][:-3]
    hr_nx=Hours[num+1][:-3]
    df_hr=df_tar_feats.between_time(Hours[num],Hours[num+1])
    print(Hours[num], 'to', Hours[num+1], len(df_hr), max(df_hr['Targ']), df_hr['Targ'].mean(), df_hr['Targ'].std())

00:00 to 00:30 2192 0.0 0.0 0.0
01:00 to 01:30 2192 0.0 0.0 0.0
02:00 to 02:30 2192 0.0 0.0 0.0
03:00 to 03:30 2192 0.0 0.0 0.0
04:00 to 04:30 2192 11.9 0.30305656934306585 1.2397216897715433
05:00 to 05:30 2192 56.400000000000006 4.2052463503649635 9.305438054841794
06:00 to 06:30 2191 138.7 19.0628023733455 29.50632033828794
07:00 to 07:30 2190 220.60000000000002 47.74899543378996 57.90973084733816
08:00 to 08:30 2190 287.5 82.67557077625571 85.36399499440849
09:00 to 09:30 2192 308.2 109.35205291970803 104.40599979690991
10:00 to 10:30 2192 312.0 122.41706204379562 111.74838562406212
11:00 to 11:30 2192 312.6 125.3797445255477 112.51787524840006
12:00 to 12:30 2192 312.4 121.10780109489042 109.74505969362221
13:00 to 13:30 2192 306.79999999999995 108.93713503649634 101.33405961100473
14:00 to 14:30 2192 281.79999999999995 82.8536040145987 83.52415194298344
15:00 to 15:30 2192 216.39999999999998 48.115921532846706 58.14388358014166
16:00 to 16:30 2192 132.0 19.988686131386842 30.610146930776335
17:00 to 17:30 2192 56.699999999999996 4.7412408759124105 9.923530344942524
18:00 to 18:30 2192 17.1 0.409990875912409 1.629782041386874
19:00 to 19:30 2192 0.1 4.5620437956204383e-05 0.0021358941442919414
20:00 to 20:30 2192 0.0 0.0 0.0
21:00 to 21:30 2192 0.0 0.0 0.0
22:00 to 22:30 2192 0.0 0.0 0.0
23:00 to 23:30 2192 0.0 0.0 0.0

All hours with instances 2192 except 6=2191, 7=8=2190

Hours with zero power: 20, 21, 22, 23, 00, 1, 2, 3

Hour 19 is with lowest solar power output and highest variability, max=0.1MW, mean=4.56e-05MW, std=0.0021MW

Hour 11 is with highest solar power output, max=312.6MW,  mean124.603MW, std=112.518MW

00:00 to 00:30 2192 0.0 0.0 0.0
01:00 to 01:30 2192 0.0 0.0 0.0
02:00 to 02:30 2192 0.0 0.0 0.0
03:00 to 03:30 2192 0.0 0.0 0.0
04:00 to 04:30 2192 11.9 0.30305656934306585 1.2397216897715433
05:00 to 05:30 2192 56.400000000000006 4.2052463503649635 9.305438054841794
06:00 to 06:30 2191 138.7 19.0628023733455 29.50632033828794
07:00 to 07:30 2190 220.60000000000002 47.74899543378996 57.90973084733816
08:00 to 08:30 2190 287.5 82.67557077625571 85.36399499440849
09:00 to 09:30 2192 308.2 109.35205291970803 104.40599979690991
10:00 to 10:30 2192 312.0 122.41706204379562 111.74838562406212
11:00 to 11:30 2192 312.6 125.3797445255477 112.51787524840006
12:00 to 12:30 2192 312.4 121.10780109489042 109.74505969362221
13:00 to 13:30 2192 306.79999999999995 108.93713503649634 101.33405961100473
14:00 to 14:30 2192 281.79999999999995 82.8536040145987 83.52415194298344
15:00 to 15:30 2192 216.39999999999998 48.115921532846706 58.14388358014166
16:00 to 16:30 2192 132.0 19.988686131386842 30.610146930776335
17:00 to 17:30 2192 56.699999999999996 4.7412408759124105 9.923530344942524
18:00 to 18:30 2192 17.1 0.409990875912409 1.629782041386874
19:00 to 19:30 2192 0.1 4.5620437956204383e-05 0.0021358941442919414
20:00 to 20:30 2192 0.0 0.0 0.0
21:00 to 21:30 2192 0.0 0.0 0.0
22:00 to 22:30 2192 0.0 0.0 0.0
23:00 to 23:30 2192 0.0 0.0 0.0



Every 2hours:

00:00 to 02:00 5480 0.0 0.0 0.0
02:00 to 04:00 5480 1.8 0.007226277372262774 0.07013901589457375
04:00 to 06:00 5480 93.2 4.500401459854008 12.347724349379707
06:00 to 08:00 5476 257.0 41.60916727538358 57.93494503036976
08:00 to 10:00 5478 310.6 100.97141292442477 99.91578351113283
10:00 to 12:00 5480 312.6 123.7288138686132 111.9208211310336
12:00 to 14:00 5480 312.4 110.25538321167892 103.03826406843969
14:00 to 16:00 5480 281.79999999999995 57.49456204379563 69.98268708535294
16:00 to 18:00 5480 132.0 10.042098540145949 21.980805801111305
18:00 to 20:00 5480 17.1 0.16401459854014608 1.0500144428241207
20:00 to 22:00 5480 0.0 0.0 0.0
22:00 to 00:00 5480 0.0 0.0 0.0

In [147]:
R=dfddf ### Just to stop to check out before run following cells

NameError: name 'dfddf' is not defined

In [ ]:
from sklearn.ensemble import GradientBoostingRegressor

est = GradientBoostingRegressor(n_estimators=100, learning_rate=0.05,
                                max_depth=8, random_state=0, subsample=0.9, loss='ls').fit(X_train, Y_train)
pred_Y=est.predict(X_test)
mse=mean_squared_error(Y_test, pred_Y)  
nRMSE=np.sqrt(mse)/Targ.mean()

print(mse, nRMSE)

In [ ]:
# import xgboost as xgb
# model.fit(X_train, Y_train)

from xgboost.sklearn import XGBRegressor

model=XGBRegressor(n_estimators=200, learning_rate=0.05, max_depth=8, random_state=0,
                 subsample=0.9, colsample_bytree=1.0, loss='ls').fit(X_train, Y_train)


model.score(X_test,Y_test)

pred_Yxgb=model.predict(X_test)
mse=mean_squared_error(Y_test, pred_Yxgb)  
nRMSE=np.sqrt(mse)/Targ.mean()
# nRMSE=np.sqrt(mse)/max(Targ)

print(mse, nRMSE)

In [ ]:
#print(mse, nRMSE)

By XGB, nRMSE=1.3115674 > 1.2729759 from GB, but XGBoost here without any tuning for its parameters

Cross-validation for GBoosting: 2folds for each of 100 candidates, totalling 200 fits (each fold 1 year)

In [ ]:
R=dfddf ### Just to stop to check out before run following cells

In [ ]:
from sklearn import metrics   ##Additional scklearn functions
from sklearn.model_selection import cross_validate
from sklearn.model_selection import GridSearchCV   #Perforing grid search
from sklearn.ensemble import GradientBoostingRegressor
GB_model = GradientBoostingRegressor()

Xgrid_train=df_feats.loc['1/1/2016':'12/31/2017']
Ygrid_train=Targ.loc['1/1/2016':'12/31/2017']

test_params = {'n_estimators':[100, 200, 300, 400, 500], 'learning_rate':[0.05,0.1, 0.2, 0.3, 0.5], 
               'max_depth':[2,4,8,12]}

# grid = GridSearchCV(estimator = GB_model, param_grid = test_params, n_jobs=4, 
#                     scoring='neg_mean_squared_error',cv=3, verbose=3)

grid = GridSearchCV(estimator = GB_model, param_grid = test_params, n_jobs=4, 
                    scoring='neg_mean_squared_error',cv=2, verbose=3)

grid.fit(Xgrid_train,Ygrid_train)
print(grid.best_params_)

In [ ]:
R=dfddf ### Just to stop to check out before run following cells

Cross-validation for XGBoost: 2folds for each 400 candidates (total 1200 fits), takes almost 2hours

In [ ]:
from sklearn import metrics   ##Additional scklearn functions
from sklearn.model_selection import cross_validate
from sklearn.model_selection import GridSearchCV   #Perforing grid search
from xgboost.sklearn import XGBRegressor
xgb_model = XGBRegressor()

Xgrid_train=df_feats.loc['1/1/2016':'12/31/2017']
Ygrid_train=Targ.loc['1/1/2016':'12/31/2017']

# test_params = {'n_estimators':[100, 200, 300, 400, 500], 'learning_rate':[0.05,0.1, 0.2, 0.3, 0.5], 
#                'max_depth':[2,4,8,12],'subsample': [0.9, 1.0], 'colsample_bytree': [0.9, 1.0]}

test_params = {'n_estimators':[100, 200, 300, 500], 'learning_rate':[0.05,0.1, 0.2], 
               'max_depth':[2,4,8,10]}

grid = GridSearchCV(estimator = xgb_model, param_grid = test_params, n_jobs=4, 
                    scoring='neg_mean_squared_error',cv=2, verbose=3)

grid.fit(Xgrid_train,Ygrid_train)
print(grid.best_params_)

In [ ]:
##### Printing out the CV results
print("Best: %f using %s" % (grid.best_score_, grid.best_params_))

means = grid.cv_results_['mean_test_score']
stds = grid.cv_results_['std_test_score']
params = grid.cv_results_['params']

for mean, stdev, param in zip(means, stds, params):
    print("%f (%f) with: %r" % (mean, stdev, param))