Training and forecasting the solar power of Hokkaido Island in Japna
Training 2017, Forecast 2018

https://stackoverflow.com/questions/35139108/how-to-install-xgboost-in-anaconda-python-windows-platform

In [1]:
import pandas as pd
import numpy as np
import datetime as dt
import csv 
import matplotlib.pyplot as plt
import pytz
import xgboost as xgb

In [2]:
import os
cwd = os.getcwd()
cwd
# os.chdir('pvinhokkaidodatadistribution')
# C:\Users\Mhdella\Google Drive\Jupyter Folder\PV_Hokkaido_forecast_contest\
os.chdir('C:\\Users\\Mhdella\\Google Drive\\Jupyter Folder\\PV_Hokkaido_forecast_contest\\pvinhokkaidodatadistribution')
nwd=os.getcwd()
nwd

'C:\\Users\\Mhdella\\Google Drive\\Jupyter Folder\\PV_Hokkaido_forecast_contest\\pvinhokkaidodatadistribution'

In [3]:
# file_name='Merg_Ens_Agg_42_44_mes17_18.csv'
# file_name='Merg_Ens_Agg_43_mes17_18.csv'

# file_name='Merg_Ens_Agg_42_44_mes16_17_18.csv'
file_name='Merg_Ens_mmaxmin_Agg_42_44_mes16_18.csv'

# file_name='Merg_Res_Comb_S1_S2_2018_tz_Jp.csv'
# file_mane='Merg_Res_Comb_S1_S2_2017_tz_Jp.csv'

df_hok=pd.read_csv(file_name) 
df_hok.head()
# df_hok.tail()

,DATE,TIME,S1[MW],S2[MW],solar[kW/m2],temp[deg C],solar[kW/m2].1,temp[deg C].1,solar[kW/m2].2,temp[deg C].2,...,t2m.2,asn.2,sd.2,ssrdc.2,ssrd.2,tcc.2,tciw.2,tclw.2,tp.2,wind_speed.2
0,1/1/2016,9:00:00,54.7,78.4,0.159228,-1.2,0.276627,0.0,0.339371,-5.9,...,-13.909399,0.600965,7.450000e-09,57.319398,30.413241,0.000000,0.000000,0.000000,0.000000e+00,7.704484
1,1/1/2016,9:30:00,113.8,89.0,0.221269,-0.3,0.307764,0.1,0.297246,-4.4,...,-12.694835,0.600870,7.450000e-09,104.414120,55.211142,0.037510,0.000396,0.000012,2.690000e-07,7.772519
2,1/1/2016,10:00:00,115.9,97.3,0.231619,-0.5,0.354492,0.7,0.320564,-2.3,...,-11.480271,0.600775,7.450000e-09,151.508843,80.009043,0.075021,0.000793,0.000023,5.390000e-07,7.840554
3,1/1/2016,10:30:00,139.5,100.6,0.205909,-0.4,0.363168,0.8,0.306980,-1.9,...,-10.265707,0.600680,7.450000e-09,198.603565,104.806944,0.112531,0.001189,0.000034,8.080000e-07,7.908589
4,1/1/2016,11:00:00,125.7,96.8,0.277444,-0.2,0.358989,0.6,0.237579,-3.1,...,-9.051143,0.600586,7.450000e-09,245.698287,129.604846,0.150041,0.001585,0.000046,1.080000e-06,7.976625

In [4]:
#### This cell just to check out the dataset with different coordination lat 43 and lat42-44 from ECMWF
df_hok1=pd.read_csv('Merg_Ens_Agg_42_44_mes17_18.csv') 
df_hok2=pd.read_csv('Merg_Ens_Agg_43_mes17_18.csv')

df_mns= {'col1': df_hok1.mean(), 'col2': df_hok2.mean()}
# df_mns

https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.GradientBoostingRegressor.html

https://scikit-learn.org/stable/auto_examples/ensemble/plot_gradient_boosting_regression.html#sphx-glr-auto-examples-ensemble-plot-gradient-boosting-regression-py

In [5]:
import sklearn 
import numpy as np
from sklearn.metrics import mean_squared_error
# X, y = make_friedman1(n_samples=1200, random_state=0, noise=1.0)
# X, y = make_friedman1(n_samples=1200, random_state=0, noise=1.0)
df_hok.head()

,DATE,TIME,S1[MW],S2[MW],solar[kW/m2],temp[deg C],solar[kW/m2].1,temp[deg C].1,solar[kW/m2].2,temp[deg C].2,...,t2m.2,asn.2,sd.2,ssrdc.2,ssrd.2,tcc.2,tciw.2,tclw.2,tp.2,wind_speed.2
0,1/1/2016,9:00:00,54.7,78.4,0.159228,-1.2,0.276627,0.0,0.339371,-5.9,...,-13.909399,0.600965,7.450000e-09,57.319398,30.413241,0.000000,0.000000,0.000000,0.000000e+00,7.704484
1,1/1/2016,9:30:00,113.8,89.0,0.221269,-0.3,0.307764,0.1,0.297246,-4.4,...,-12.694835,0.600870,7.450000e-09,104.414120,55.211142,0.037510,0.000396,0.000012,2.690000e-07,7.772519
2,1/1/2016,10:00:00,115.9,97.3,0.231619,-0.5,0.354492,0.7,0.320564,-2.3,...,-11.480271,0.600775,7.450000e-09,151.508843,80.009043,0.075021,0.000793,0.000023,5.390000e-07,7.840554
3,1/1/2016,10:30:00,139.5,100.6,0.205909,-0.4,0.363168,0.8,0.306980,-1.9,...,-10.265707,0.600680,7.450000e-09,198.603565,104.806944,0.112531,0.001189,0.000034,8.080000e-07,7.908589
4,1/1/2016,11:00:00,125.7,96.8,0.277444,-0.2,0.358989,0.6,0.237579,-3.1,...,-9.051143,0.600586,7.450000e-09,245.698287,129.604846,0.150041,0.001585,0.000046,1.080000e-06,7.976625

In [6]:
print(list(df_hok))

['DATE', 'TIME', 'S1[MW]', 'S2[MW]', 'solar[kW/m2]', 'temp[deg C]', 'solar[kW/m2].1', 'temp[deg C].1', 'solar[kW/m2].2', 'temp[deg C].2', 'solar[kW/m2].3', 'temp[deg C].3', 'u10', 'v10', 't2m', 'asn', 'sd', 'ssrdc', 'ssrd', 'tcc', 'tciw', 'tclw', 'tp', 'wind_speed', 'u10.1', 'v10.1', 't2m.1', 'asn.1', 'sd.1', 'ssrdc.1', 'ssrd.1', 'tcc.1', 'tciw.1', 'tclw.1', 'tp.1', 'wind_speed.1', 'u10.2', 'v10.2', 't2m.2', 'asn.2', 'sd.2', 'ssrdc.2', 'ssrd.2', 'tcc.2', 'tciw.2', 'tclw.2', 'tp.2', 'wind_speed.2']

In [7]:
#### df_feats=df_hok[df_hok['ssrdc'] != 0] ## dropping night hours, when clear-sky solar irradiance (SSRDC) forecasts=0, and this can be applied in real forecasts  

#### df_feats=df_hok.set_index('DATE')

############################# Not dropping night hours

df_tar_feats=df_hok.set_index(pd.to_datetime(df_hok['DATE'] + ' ' + df_hok['TIME']))

############## In case of forecast solar power  #######

Targ=df_tar_feats['S1[MW]']+df_tar_feats['S2[MW]']
Targ = Targ.replace(np.nan, 0, regex=True)

df_feats=df_tar_feats[['u10', 'v10', 't2m', 'asn', 'sd', 'ssrdc', 'ssrd', 'tcc', 'tciw', 'tclw', 'tp', 'wind_speed', 
             'u10.1', 'v10.1', 't2m.1', 'asn.1', 'sd.1', 'ssrdc.1', 'ssrd.1', 'tcc.1', 'tciw.1', 'tclw.1', 'tp.1', 'wind_speed.1', 
             'u10.2', 'v10.2', 't2m.2', 'asn.2', 'sd.2', 'ssrdc.2', 'ssrd.2', 'tcc.2', 'tciw.2', 'tclw.2', 'tp.2', 'wind_speed.2']]
############### In case of forecast solar irradiance  #######

# Targ=df_tar_feats['ssrd']  #ssrd is the mean of ssrd data from all ensemble members
# df_feats=df_tar_feats[['u10', 'v10', 't2m', 'asn', 'sd', 'ssrdc', 'tcc', 'tciw', 'tclw', 'tp', 'wind_speed', 
#              'u10.1', 'v10.1', 't2m.1', 'asn.1', 'sd.1', 'ssrdc.1', 'tcc.1', 'tciw.1', 'tclw.1', 'tp.1', 'wind_speed.1', 
#              'u10.2', 'v10.2', 't2m.2', 'asn.2', 'sd.2', 'ssrdc.2', 'tcc.2', 'tciw.2', 'tclw.2', 'tp.2', 'wind_speed.2']]


df_tar_feats.insert(loc=0, column='Targ', value=Targ)

df_feats.head()
df_feats.tail()

print(len(list(df_feats)), len(list(df_tar_feats)))
# Targ.tail()

36 49

In [8]:
len(df_feats)
# len(Targ)
print(len(Targ), max(Targ), Targ.mean())

52603 312.6 37.385689029143066

In [9]:
data_hr=df_tar_feats  #this without measurements features

print(len(list(data_hr)))

49

In [22]:
ind_date_time= pd.date_range('2019-03-08 00:00','2019-03-09 00:00',freq='120T')

In [21]:
## R=dfddf ### Just to stop to check out before run forecast models

# ind_date_time= pd.date_range('2019-03-08 00:00','2019-03-09 00:00',freq='60T')
ind_date_time= pd.date_range('2019-03-08 00:00','2019-03-09 00:00',freq='120T')

Hours= ind_date_time.strftime('%H:%M')

# for num in range(0,len(Hours)-1):
for num in range(6,7):
#       print (num)
    hr=Hours[num][:-3]
    hr_nx=Hours[num+1][:-3]
    df_hr=data_hr.between_time(Hours[num],Hours[num+1])
    
#print(Hours[num], 'to', Hours[num+1], len(df_hr), max(df_hr['Targ']), df_hr['Targ'].mean(), df_hr['Targ'].std() )
df_hr.head(8)

,Targ,DATE,TIME,S1[MW],S2[MW],solar[kW/m2],temp[deg C],solar[kW/m2].1,temp[deg C].1,solar[kW/m2].2,...,t2m.2,asn.2,sd.2,ssrdc.2,ssrd.2,tcc.2,tciw.2,tclw.2,tp.2,wind_speed.2
2016-01-01 12:00:00,185.1,1/1/2016,12:00:00,93.6,91.5,0.185560,-1.1,0.507231,2.2,0.189717,...,-6.622015,0.600396,7.450000e-09,339.887731,179.200648,0.225062,0.002378,0.000069,1.620000e-06,8.112695
2016-01-01 12:30:00,203.7,1/1/2016,12:30:00,130.6,73.1,0.187354,-0.7,0.411599,2.2,0.141504,...,-6.873384,0.600497,7.450000e-09,326.444884,171.520961,0.204103,0.002048,0.000063,1.350000e-06,8.091706
2016-01-01 13:00:00,208.8,1/1/2016,13:00:00,133.1,75.7,0.173216,-0.8,0.357569,1.8,0.131747,...,-7.124752,0.600598,7.450000e-09,313.002037,163.841273,0.183144,0.001717,0.000057,1.080000e-06,8.070717
2016-01-01 13:30:00,170.9,1/1/2016,13:30:00,99.3,71.6,0.108650,-1.0,0.307997,1.3,0.094259,...,-7.376120,0.600698,7.450000e-09,299.559190,156.161586,0.162185,0.001387,0.000052,8.080000e-07,8.049729
2016-01-01 14:00:00,128.6,1/1/2016,14:00:00,79.5,49.1,0.066130,-1.0,0.237548,1.2,0.183076,...,-7.627488,0.600799,7.450000e-09,286.116343,148.481898,0.141227,0.001057,0.000046,5.390000e-07,8.028740
2016-01-02 12:00:00,68.6,1/2/2016,12:00:00,41.5,27.1,0.153839,2.4,0.159056,4.4,0.319912,...,-5.582068,0.601667,7.450000e-09,323.773264,68.071898,0.462622,0.006468,0.000069,4.690000e-05,4.532811
2016-01-02 12:30:00,106.7,1/2/2016,12:30:00,62.1,44.6,0.111115,2.0,0.335384,4.9,0.343587,...,-5.273937,0.601293,7.450000e-09,311.628526,66.472955,0.389893,0.005390,0.000057,3.920000e-05,4.510920
2016-01-02 13:00:00,133.9,1/2/2016,13:00:00,76.4,57.5,0.047315,2.0,0.239896,5.2,0.349615,...,-4.965806,0.600919,7.450000e-09,299.483789,64.874012,0.317163,0.004312,0.000046,3.150000e-05,4.489029

In [11]:
####Select features of the data 
Targ=df_hr['Targ']
df_feats_w_mes=df_hr.drop('Targ', axis=1) #Features including measurements and weather forecasts
df_feats_no_mes =df_hr.drop(df_tar_feats.columns[range(0,13)], axis=1)  #Features of weather forecasts only
print(len(df_feats_no_mes), len(df_feats_w_mes), len(Targ))
# print(len(list(df_feats_no_mes)), len(list(df_feats_w_mes)), len(list(Targ)))

# df_feats=df_feats_w_mes  ## the measurements lenght is less than the weather since there are not exist in forecast period
df_feats=df_feats_no_mes   
df_feats.describe()

5480 5480 5480

,u10,v10,t2m,asn,sd,ssrdc,ssrd,tcc,tciw,tclw,...,t2m.2,asn.2,sd.2,ssrdc.2,ssrd.2,tcc.2,tciw.2,tclw.2,tp.2,wind_speed.2
count,5480.000000,5480.000000,5480.000000,5480.000000,5480.000000,5480.000000,5480.000000,5480.000000,5.480000e+03,5480.000000,...,5480.000000,5480.000000,5.480000e+03,5480.000000,5480.000000,5480.000000,5.480000e+03,5.480000e+03,5.480000e+03,5480.000000
mean,1.599249,0.362013,8.637853,0.853826,0.014590,541.182540,384.464005,0.684138,3.705003e-02,0.073257,...,3.579648,0.776134,2.487865e-09,510.532711,221.547580,0.222275,3.574398e-03,3.658356e-03,2.148833e-05,6.199876
std,3.296486,2.921305,8.982846,0.032808,0.023288,190.184139,180.444779,0.262147,5.568754e-02,0.105956,...,9.569540,0.110146,3.513883e-09,187.817898,160.840960,0.304806,1.255843e-02,1.119051e-02,1.650965e-04,3.577684
min,-10.305952,-11.118870,-10.447368,0.725971,0.000000,158.951860,25.592518,0.005045,-5.960000e-08,0.000003,...,-20.138759,0.544511,0.000000e+00,139.804645,0.000000,0.000000,-5.960000e-08,0.000000e+00,0.000000e+00,0.148524
25%,-0.787531,-1.483646,0.276135,0.833898,0.000000,376.863403,243.112020,0.493620,5.036984e-03,0.005673,...,-4.738092,0.689238,0.000000e+00,347.763517,97.033070,0.000946,-5.960000e-08,5.960000e-08,0.000000e+00,3.564470
50%,1.623544,0.394751,9.250559,0.869046,0.000064,562.815930,366.373950,0.715026,1.752544e-02,0.026037,...,4.190429,0.797485,0.000000e+00,529.524248,185.354392,0.060344,3.170000e-05,3.960000e-05,1.860000e-09,5.689373
75%,3.897837,2.456526,16.727726,0.880001,0.023580,695.733470,510.062053,0.929529,3.982412e-02,0.099925,...,12.011972,0.879997,7.450000e-09,663.986971,312.530077,0.341249,8.829015e-04,1.720545e-03,1.860000e-09,8.228420
max,12.677865,9.583614,25.894714,0.880003,0.091110,917.312000,901.954500,1.000000,4.604178e-01,0.764093,...,21.586664,0.880002,7.450000e-09,894.821111,877.961481,1.000000,2.264951e-01,1.396809e-01,4.672943e-03,24.363045

In [12]:
X_train=df_feats.loc['1/1/2016':'12/31/2016']
X_test=df_feats.loc['1/1/2017':'12/31/2017']

# X_train=df_feats.loc['1/1/2017':'12/31/2017']
# X_test=df_feats.loc['1/1/2018':'12/31/2018']

Y_train=Targ.loc['1/1/2016':'12/31/2016']
Y_test=Targ.loc['1/1/2017':'12/31/2017']

# Y_train=Targ.loc['1/1/2017':'12/31/2017']
# Y_test=Targ.loc['1/1/2018':'12/31/2018']

X_train.head()
# X_train.tail()
# len(X_train)

# Y_train.head()
# len(Y_train)
Y_train.tail()

2016-12-31 10:00:00    124.8
2016-12-31 10:30:00    145.1
2016-12-31 11:00:00    157.0
2016-12-31 11:30:00    157.4
2016-12-31 12:00:00    163.3
Name: Targ, dtype: float64

In [13]:
len(df_hr)
hr

'10'

In [14]:
def model_hr01234(Y_train, X_train, Y_test, X_test):
    from xgboost.sklearn import XGBRegressor
    model=XGBRegressor(n_estimators=200, learning_rate=0.05, max_depth=8, random_state=0,
                 subsample=0.9, colsample_bytree=1.0, loss='ls').fit(X_train, Y_train)
    model.score(X_test,Y_test)

    pred_Yxgb=model.predict(X_test)
    mse=mean_squared_error(Y_test, pred_Yxgb)  
    nRMSE=np.sqrt(mse)/Targ.mean()
    # nRMSE=np.sqrt(mse)/max(Targ)
    print(mse, nRMSE)
    return mse, nRMSE

In [17]:
from Hokk_Hourly_Forecast_Models import model_hr222300123, model_hr456, model_hr789, model_hr101112,
model_hr131415, model_hr161718, model_hr192021

if int(hr)<4:
    print('Yes4')
    model_hr222300123(Y_train, X_train, Y_test, X_test, Targ)
elif int(hr)>=3 and int(hr_nx)<=6:
    print('Yes6')
    model_hr456(Y_train, X_train, Y_test, X_test, Targ)
elif int(hr)>=7 and int(hr_nx)<=9:
    print('Yes9')
    model_hr789(Y_train, X_train, Y_test, X_test, Targ)
elif int(hr)>=10 and int(hr_nx)<=12:
    print('Yes12')
    model_hr101112(Y_train, X_train, Y_test, X_test, Targ)
elif int(hr)>=13 and int(hr_nx)<=15:
    print('Yes15')
    model_hr131415(Y_train, X_train, Y_test, X_test, Targ)
elif int(hr)>=16 and int(hr_nx)<=18:
    print('Yes18')
    model_hr161718(Y_train, X_train, Y_test, X_test, Targ)
elif int(hr)>=19 and int(hr_nx)<=21:
    print('Yes21')
    model_hr192021(Y_train, X_train, Y_test, X_test, Targ)
elif int(hr)>=20 and int(hr_nx)<=23:
    print('Yes00')
    model_hr222300123(Y_train, X_train, Y_test, X_test, Targ)
else:
    print('No')

No

In [20]:
# Y_test
int(hr)
int(hr_nx)
# hr=8
# if hr>=5 and hr<=7:
#     print('Yes')
# else:print('NO')

12

In [ ]:
Y_test