Split Date-Time to DATE and TIME columns

In [1]:
import pandas as pd
import numpy as np
import datetime as dt
import csv 
import matplotlib.pyplot as plt
import pytz

In [2]:
import os
cwd = os.getcwd()
cwd
# os.chdir('pvinhokkaidodatadistribution')
# C:\Users\Mhdella\Google Drive\Jupyter Folder\PV_Hokkaido_forecast_contest\
os.chdir('C:\\Users\\Mhdella\\Google Drive\\Jupyter Folder\\PV_Hokkaido_forecast_contest\\pvinhokkaidodatadistribution')
nwd=os.getcwd()
nwd

'C:\\Users\\Mhdella\\Google Drive\\Jupyter Folder\\PV_Hokkaido_forecast_contest\\pvinhokkaidodatadistribution'

In [3]:
# file_name='Merg_Ens_Agg_42_44_mes17_18.csv'
# file_name='Merg_Ens_Agg_43_mes17_18.csv'
# file_name='Merg_Res_Comb_S1_S2_2018_tz_Jp.csv'
# file_name='Merg_Res_Comb_S1_S2_2017_tz_Jp.csv'
# file_name='Merg_Ens_Agg_42_44_mes16.csv'
file_name='Merg_Ens_mmaxmin_Agg_42_44_mes16_18.csv'


Data_Hokk=pd.read_csv(file_name,index_col=0) 

Data_Hokk.head()

,S1[MW],S2[MW],solar[kW/m2],temp[deg C],solar[kW/m2].1,temp[deg C].1,solar[kW/m2].2,temp[deg C].2,solar[kW/m2].3,temp[deg C].3,...,t2m.2,asn.2,sd.2,ssrdc.2,ssrd.2,tcc.2,tciw.2,tclw.2,tp.2,wind_speed.2
DATE_TIME,,,,,,,,,,,,,,,,,,,,,
2016-01-01 09:00:00,54.7,78.4,0.159228,-1.2,0.276627,0.0,0.339371,-5.9,0.276318,-4.5,...,-13.909399,0.600965,7.450581e-09,57.319398,30.413241,0.000000,0.000000,0.000000,0.000000e+00,7.704484
2016-01-01 09:30:00,113.8,89.0,0.221269,-0.3,0.307764,0.1,0.297246,-4.4,0.322007,-3.3,...,-12.694835,0.600870,7.450581e-09,104.414120,55.211142,0.037510,0.000396,0.000011,2.694627e-07,7.772519
2016-01-01 10:00:00,115.9,97.3,0.231619,-0.5,0.354492,0.7,0.320564,-2.3,0.360174,-1.9,...,-11.480271,0.600775,7.450581e-09,151.508843,80.009043,0.075021,0.000793,0.000023,5.389253e-07,7.840554
2016-01-01 10:30:00,139.5,100.6,0.205909,-0.4,0.363168,0.8,0.306980,-1.9,0.399243,-0.8,...,-10.265707,0.600680,7.450581e-09,198.603565,104.806944,0.112531,0.001189,0.000034,8.083880e-07,7.908589
2016-01-01 11:00:00,125.7,96.8,0.277444,-0.2,0.358989,0.6,0.237579,-3.1,0.412188,-0.3,...,-9.051143,0.600586,7.450581e-09,245.698287,129.604846,0.150041,0.001585,0.000046,1.077851e-06,7.976625

In [4]:
if 'Agg' in file_name:
    del Data_Hokk['time']
else:
    print('No additional time column need to be deleted')

In [5]:
Data_Hokk.index=pd.to_datetime(Data_Hokk.index)
Data_Hokk.index
Data_Hokk.index.date
Data_Hokk.insert(0, 'DATE', Data_Hokk.index.date)
Data_Hokk.insert(1, 'TIME', Data_Hokk.index.time)

Data_Hokk.head()

,DATE,TIME,S1[MW],S2[MW],solar[kW/m2],temp[deg C],solar[kW/m2].1,temp[deg C].1,solar[kW/m2].2,temp[deg C].2,...,t2m.2,asn.2,sd.2,ssrdc.2,ssrd.2,tcc.2,tciw.2,tclw.2,tp.2,wind_speed.2
DATE_TIME,,,,,,,,,,,,,,,,,,,,,
2016-01-01 09:00:00,2016-01-01,09:00:00,54.7,78.4,0.159228,-1.2,0.276627,0.0,0.339371,-5.9,...,-13.909399,0.600965,7.450581e-09,57.319398,30.413241,0.000000,0.000000,0.000000,0.000000e+00,7.704484
2016-01-01 09:30:00,2016-01-01,09:30:00,113.8,89.0,0.221269,-0.3,0.307764,0.1,0.297246,-4.4,...,-12.694835,0.600870,7.450581e-09,104.414120,55.211142,0.037510,0.000396,0.000011,2.694627e-07,7.772519
2016-01-01 10:00:00,2016-01-01,10:00:00,115.9,97.3,0.231619,-0.5,0.354492,0.7,0.320564,-2.3,...,-11.480271,0.600775,7.450581e-09,151.508843,80.009043,0.075021,0.000793,0.000023,5.389253e-07,7.840554
2016-01-01 10:30:00,2016-01-01,10:30:00,139.5,100.6,0.205909,-0.4,0.363168,0.8,0.306980,-1.9,...,-10.265707,0.600680,7.450581e-09,198.603565,104.806944,0.112531,0.001189,0.000034,8.083880e-07,7.908589
2016-01-01 11:00:00,2016-01-01,11:00:00,125.7,96.8,0.277444,-0.2,0.358989,0.6,0.237579,-3.1,...,-9.051143,0.600586,7.450581e-09,245.698287,129.604846,0.150041,0.001585,0.000046,1.077851e-06,7.976625

In [7]:
print(len(Data_Hokk)) #number of rows
print(len(Data_Hokk.columns))  #number of columns

35070
48

In [9]:
### Data_Hokk.to_csv(file_name, encoding='utf-8', index=False)