WEMC TECH BLOG #1: INSTALLING PYTHON AND PACKAGES

In this series of technical blog posts, we will be looking at using open source tools to examine energy
and climate data.
The examples will be mostly using Python3 and based on OSX/Linux environment, however they
should translate to Windows too.

To check if you have Python3 installed, enter the following into a terminal window:python --version

https://stackoverflow.com/questions/38918749/netcdf4-import-not-being-found-by-python

conda install netcdf4     (in Anaconda Prompt)

https://anaconda.org/anaconda/xarray

conda install -c anaconda xarray   (in Anaconda Prompt)

In [5]:
import netCDF4
import matplotlib
import numpy as np
import xarray as xr

WEMC TECH BLOG #2: PLOTTING NETCDF WITH PYTHON

In [7]:
# importing of NetCDF files
import netCDF4
# plotting and data visualisations
# n-dimensional arrays
import numpy as np
# high level functions for working with NetCDF files
import xarray as xr
# add colour labels to plot
import matplotlib.patches as mpatches

In [10]:
# load NetCDF file into variable - using xarray open dataset function
# if using jupyter, make sure NetCDF files are in same directory
# ds1 = xr.open_dataset('ERA5_analysis_10U_165_2008.nc')
# ds2 = xr.open_dataset('ERA5_analysis_10V_166_2008.nc')

WEMC TECH BLOG #3: ERA5 10M/100M ANALYSIS

In [11]:
# importing of NetCDF files
import netCDF4
# plotting and data visualisations
from matplotlib import pyplot as plt
# n-dimensional arrays
import numpy as np
# high level functions for working with NetCDF files
import xarray as xr

In [13]:
# load NetCDF file into variable - using xarray open dataset function
# coef = xr.open_dataset('/Users/user/Documents/ERA5/yearly_complete/allyears/coef.nc')

WEMC TECH BLOG #4: CALCULATING EU COUNTRY AVERAGES WITH ERA5 AND NUTS

To install this package with conda run one of the following:

conda install -c conda-forge iris
conda install -c conda-forge/label/gcc7 iris
conda install -c conda-forge/label/broken iris
conda install -c conda-forge/label/cf201901 iris 

conda install -c conda-forge geopandas

In [26]:
# import packages
import iris
import geopandas as gpd
import numpy as np
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import iris.plot as iplt
import iris.quickplot as qplt
import iris.pandas
import os

In [32]:
# read the NUTS shapefile and extract the polygons for a individual countries
# https://cds.climate.copernicus.eu/#!/home
# https://ec.europa.eu/eurostat/web/gisco/geodata/reference-data/administrative-units-statistical-units/nuts
# nuts=gpd.read_file('ref-nuts-2016-20m.shp/NUTS_RG_20M_2016_4258_LEVL_0.shp')
nuts=gpd.read_file('ref-nuts-2016-20m.shp/NUTS_RG_20M_2016_4326_LEVL_0.shp')

In [34]:
nuts

,NUTS_ID,LEVL_CODE,CNTR_CODE,NUTS_NAME,FID,geometry
0,ES,0,ES,ESPAÃA,ES,"(POLYGON ((-7.03184 43.54447, -6.29214 43.5699..."
1,FI,0,FI,SUOMI / FINLAND,FI,"(POLYGON ((28.92968 69.0519, 28.62465 68.93047..."
2,IS,0,IS,ÃSLAND,IS,"POLYGON ((-22.0074 63.83599, -22.13087 63.8366..."
3,FR,0,FR,FRANCE,FR,"(POLYGON ((2.60704 50.91269, 2.64799 50.82501,..."
4,HR,0,HR,HRVATSKA,HR,"(POLYGON ((16.59681 46.4759, 16.85476 46.35044..."
5,HU,0,HU,MAGYARORSZÃG,HU,"POLYGON ((22.12108 48.37831, 22.15531 48.4034,..."
6,AL,0,AL,SHQIPÃRIA,AL,"POLYGON ((19.831 42.46645, 20.0763 42.55582, 2..."
7,AT,0,AT,ÃSTERREICH,AT,"POLYGON ((15.75363 48.85218, 16.29009 48.73395..."
8,BE,0,BE,BELGIQUE-BELGIÃ,BE,"POLYGON ((4.75993 51.50246, 4.864 51.43362, 5...."
9,BG,0,BG,ÐÐªÐÐÐÐ ÐÐ¯,BG,"POLYGON ((22.99717 43.80787, 23.40948 43.84985..."
10,CH,0,CH,SCHWEIZ/SUISSE/SVIZZERA,CH,"POLYGON ((8.67046 47.68486, 8.79571 47.6756, 8..."
11,CY,0,CY,ÎÎ¥Î Î¡ÎÎ£,CY,"POLYGON ((32.27382 35.06649, 32.28884 35.10503..."
12,CZ,0,CZ,ÄESKÃ REPUBLIKA,CZ,"POLYGON ((14.6188 50.8578, 14.76738 50.81985, ..."
13,DE,0,DE,DEUTSCHLAND,DE,"(POLYGON ((9.113099999999999 54.8736, 9.29405 ..."
14,DK,0,DK,DANMARK,DK,"(POLYGON ((10.19436 56.68466, 10.30688 56.6801..."
15,EE,0,EE,EESTI,EE,"(POLYGON ((25.83016 59.56406, 25.89485 59.6157..."
16,EL,0,EL,ÎÎÎÎÎÎ,EL,"(POLYGON ((26.03276 40.73026, 25.95323 40.8315..."
17,IE,0,IE,IRELAND,IE,"(POLYGON ((-7.25607 55.06703, -7.61318 54.7547..."
18,PL,0,PL,POLSKA,PL,"POLYGON ((18.95003 54.35831, 19.34181 54.37011..."
19,PT,0,PT,PORTUGAL,PT,"(POLYGON ((-8.16508 41.8183, -8.05186 41.82061..."
20,RO,0,RO,ROMÃNIA,RO,"POLYGON ((27.39117 47.5894, 27.84712 47.11681,..."
21,RS,0,RS,REPUBLIKA SRBIJA /Ð ÐÐÐ£ÐÐÐÐÐ Ð¡Ð ÐÐÐÐ,RS,"POLYGON ((20.2643 46.12637, 20.66283 45.79412,..."
22,SE,0,SE,SVERIGE,SE,"(POLYGON ((24.15513 65.81603, 23.6762 65.81662..."
23,SI,0,SI,SLOVENIJA,SI,"POLYGON ((16.37079 46.72224, 16.59681 46.4759,..."
24,SK,0,SK,SLOVENSKO,SK,"POLYGON ((19.88393 49.20418, 20.07803 49.19825..."
25,TR,0,TR,TÃRKIYE,TR,"(POLYGON ((35.5137 41.63598, 35.68335 41.66826..."
26,UK,0,UK,UNITED KINGDOM,UK,"(POLYGON ((0.21051 51.49004, 0.15174 51.51271,..."
27,IT,0,IT,ITALIA,IT,"(POLYGON ((12.47792 46.67984, 12.69064 46.6569..."
28,LI,0,LI,LIECHTENSTEIN,LI,"POLYGON ((9.476050000000001 47.0518, 9.5307499..."
29,LT,0,LT,LIETUVA,LT,"(POLYGON ((25.82139 56.05218, 25.89485 56.0001..."
30,LU,0,LU,LUXEMBOURG,LU,"POLYGON ((6.13766 50.12995, 6.17872 49.96212, ..."
31,LV,0,LV,LATVIJA,LV,"POLYGON ((27.35158 57.51824, 27.52817 57.52465..."
32,ME,0,ME,Ð¦Ð ÐÐ ÐÐÐ Ð,ME,"POLYGON ((19.22407 43.52754, 19.6706 43.19395,..."
33,MK,0,MK,ÐÐÐ ÐÐÐÐ¨ÐÐ ÐÐ£ÐÐÐ¡ÐÐÐÐÐÐ¡ÐÐ ...,MK,"POLYGON ((22.36021 42.31116, 22.44863 42.21932..."
34,MT,0,MT,MALTA,MT,"(POLYGON ((14.56429 35.8501, 14.5089 35.81338,..."
35,NL,0,NL,NEDERLAND,NL,"(POLYGON ((6.87491 53.40801, 6.92093 53.33836,..."
36,NO,0,NO,NORGE,NO,"(POLYGON ((28.92968 69.0519, 28.8195 69.126499..."

In [33]:
# set country by NUTS_ID
country = nuts[nuts['NUTS_ID'] == 'FR']